[package]
name = "some-lib"
edition.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono = { workspace = true }
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-manager-embedded = { workspace = true }
fake = { features = [ "derive", "uuid", "random_color", "chrono", "rust_decimal" ], workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
rust_decimal = { workspace = true }
gpui-table = { features = [ "fluent", "rust_decimal", "chrono" ], workspace = true }
rust-embed = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }

[lints]
workspace = true
