[package]
name = "some-lib"
edition.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-table = { features = [ "fluent" ], workspace = true }
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-manager-embedded = { workspace = true }
fake = { features = [ "derive" ], workspace = true }
rust-embed = { workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }

[lints]
workspace = true
