[package]
name = "example"
edition.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-table = { workspace = true }
gpui-table-core = { workspace = true }
gpui-table-derive = { workspace = true }

[lints]
workspace = true
