[package]
name = "spacetimedb-server"
version = "0.1.0"
edition = "2024"
license = "Unlicense"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { workspace = true }
some-lib = { path = "../some-lib" }
